# Generated by Django 3.0.4 on 2020-05-02 16:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('on_self', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttackBuf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_buf', models.SmallIntegerField(default=0)),
                ('simple_kf', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='AttackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('desc', models.TextField(blank=True, default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('orders', models.PositiveSmallIntegerField()),
                ('current_order', models.PositiveSmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('ST', 'Start'), ('MV', 'Move'), ('AT', 'Attack'), ('DF', 'Defence'), ('AB', 'Ability'), ('AC', 'Activate')], default='ST', max_length=2)),
                ('attack_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.AttackType')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GameProfile')),
                ('target_abil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Ability')),
                ('target_equip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credits', models.PositiveIntegerField()),
                ('bucta', models.PositiveIntegerField()),
                ('fuel', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpaceMap',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitClass',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.PositiveSmallIntegerField(default=0)),
                ('shields', models.PositiveSmallIntegerField(default=0)),
                ('attack', models.PositiveSmallIntegerField(default=0)),
                ('initiative', models.PositiveSmallIntegerField(default=0)),
                ('speed', models.PositiveSmallIntegerField(default=0)),
                ('unkeep', models.PositiveIntegerField(default=0)),
                ('repair', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('desc', models.TextField(blank=True, default='', max_length=2048)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unittype', to='main.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='current_params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_params', to='main.UnitParams'),
        ),
        migrations.AddField(
            model_name='unit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='main.Region'),
        ),
        migrations.AddField(
            model_name='unit',
            name='params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='main.UnitParams'),
        ),
        migrations.AddField(
            model_name='unit',
            name='target_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_location', to='main.Region'),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnitClass'),
        ),
        migrations.AddField(
            model_name='unit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.GameProfile'),
        ),
        migrations.CreateModel(
            name='SpecialEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lose_attack', models.PositiveSmallIntegerField(default=0)),
                ('move_effect', models.CharField(choices=[('START', 'START'), ('NEAR_', 'NEAR'), ('BLANK', 'BLANK')], default='BLANK', max_length=5)),
                ('deactivate', models.CharField(blank=True, choices=[('ST', 'Start'), ('MV', 'Move'), ('AT', 'Attack'), ('DF', 'Defence'), ('AB', 'Ability'), ('AC', 'Activate')], max_length=2, null=True)),
                ('attack_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='effect', to='main.AttackBuf')),
                ('target_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.UnitType')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialBuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus', models.SmallIntegerField(default=0)),
                ('kf', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('attack_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='special', to='main.AttackBuf')),
                ('target_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.UnitType')),
            ],
        ),
        migrations.CreateModel(
            name='RegionConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connect', to='main.Region')),
                ('region2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connect_to_second', to='main.Region')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='space_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='main.SpaceMap'),
        ),
        migrations.CreateModel(
            name='OrderError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_order', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error', to='main.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='target_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Region'),
        ),
        migrations.AddField(
            model_name='order',
            name='target_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_target', to='main.Unit'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Unit'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.SpaceMap'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip', to='main.Unit'),
        ),
        migrations.CreateModel(
            name='EconomicUnit',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_regular', models.BooleanField(default=False)),
                ('profit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Resource')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.GameProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attacktype',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attacktype', to='main.Unit'),
        ),
        migrations.AddField(
            model_name='attackbuf',
            name='attack_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.AttackType'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ability',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abil', to='main.Unit'),
        ),
    ]
