# Generated by Django 3.0.4 on 2020-05-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='unit',
        ),
        migrations.AddField(
            model_name='ability',
            name='unit',
            field=models.ManyToManyField(null=True, related_name='abil', to='main.Unit'),
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='unit',
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit',
            field=models.ManyToManyField(null=True, related_name='equip', to='main.Unit'),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Game'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='main.Region'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='target_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_location', to='main.Region'),
        ),
        migrations.RemoveField(
            model_name='unittype',
            name='unit',
        ),
        migrations.AddField(
            model_name='unittype',
            name='unit',
            field=models.ManyToManyField(related_name='unittype', to='main.Unit'),
        ),
    ]
