# Generated by Django 3.0.4 on 2020-05-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200502_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='unit',
            field=models.ManyToManyField(related_name='abil', to='main.Unit'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit',
            field=models.ManyToManyField(related_name='equip', to='main.Unit'),
        ),
    ]
