# Generated by Django 3.0.4 on 2020-05-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200502_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='current_params',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_params', to='main.UnitParams'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.UUIDField(auto_created=True, blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='main.Region'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='main.UnitParams'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_location', to='main.Region'),
        ),
    ]
