# Generated by Django 3.2.5 on 2021-07-17 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210717_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('e517c7a3-a075-4892-9095-6eb8bbcb5562'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('017bb60e-b237-4d07-8787-0dd8e256cdbe'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spacemap',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('861b3863-581d-4090-a2de-082aa22e1ef4'), primary_key=True, serialize=False),
        ),
    ]
