# Generated by Django 3.0.4 on 2020-05-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200502_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='current_params',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='params',
        ),
        migrations.AddField(
            model_name='unitparams',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitparams',
            name='unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='main.Unit'),
        ),
    ]
