# Generated by Django 3.2.5 on 2021-07-18 20:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210717_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('521b82be-ae16-494e-b1c9-be4cc304b65a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('e824cbec-a4fc-4bac-9513-7eb9fde5000c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='space_map',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='main.spacemap'),
        ),
        migrations.AlterField(
            model_name='spacemap',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('09508126-f292-4875-83de-01faf9299f54'), primary_key=True, serialize=False),
        ),
    ]
