# Generated by Django 3.0.4 on 2020-05-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200502_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitparams',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='main.Unit'),
        ),
    ]
